---
- hosts: app_servers
  tasks:
    - name: clone repo to app_server
      git: 
       repo: https://github.com/oyedeloy/finalproject1_2020.git
       dest: /home/ec2-user/config
       update: yes
      become: yes   

    - name: build docker image
      docker_image:
        path: /home/ec2-user/config
        name: voting

    - name: build container
      docker_container:
        name: voting_app
        image: voting
        state: started
        restart: yes       
        ports:
          - "80:80"         
        env:
           REDIS_PWD: "admin"
           REDIS: "10.7.2.105"
           REDIS_PORT: "6379"

    - name: create node-exporter container
      docker_container:
        name: node-exporter
        image: prom/node-exporter
        ports:
          - 9100:9100
        restart: yes



    
      
