---
- hosts: redis1
  tasks:
    - name: copy redis1
      copy: 
        src: redis-sentinel/redis-sentinel_1/redis.conf
        dest: /home/ec2-user/config/redis
    - name: copy sentinel1
      copy: 
        src: redis-sentinel/redis-sentinel_1/sentinel.conf
        dest: /home/ec2-user/config/sentinel
    

      become: true

- hosts: redis2
  tasks:
    - name: copy redis2
      copy: 
        src: redis-sentinel/redis-sentinel_2/redis.conf
        dest: /home/ec2-user/config/redis
    - name: copy sentinel2
      copy: 
        src: redis-sentinel/redis-sentinel_2/sentinel.conf
        dest: /home/ec2-user/config/sentinel
    

      become: true      


- hosts: redis3
  tasks:
    - name: copy redis3
      copy: 
        src: redis-sentinel/redis-sentinel_3/redis.conf
        dest: /home/ec2-user/config/redis
    - name: copy sentinel1
      copy: 
        src: redis-sentinel/redis-sentinel_3/sentinel.conf
        dest: /home/ec2-user/config/sentinel
    

      become: true

- hosts: redis4
  tasks:
    - name: copy redis4
      copy: 
        src: redis-sentinel/redis-sentinel_4/redis.conf
        dest: /home/ec2-user/config/redis
    - name: copy sentinel2
      copy: 
        src: redis-sentinel/redis-sentinel_4/sentinel.conf
        dest: /home/ec2-user/config/sentinel
    

      become: true      