---
- hosts: webserver
  tasks: 
    - name: Create a data container
      docker_container:
        name: nginx_1
        image: nginx    
        ports:
          - 80:80
        volumes:
           - ./config/nginx:/etc/nginx/conf.d
        state: started
        restart: yes

       
    - name: create node-exporter container
      docker_container:
        name: node-exporter
        image: prom/node-exporter
        ports:
          - 9100:9100
        restart: yes

      