---
- hosts: redis_nodes
  tasks:
    - name: create config folders
      shell: mkdir config
    - name: create redis folder
      shell: mkdir config/redis
    - name: create config folders
      shell: mkdir config/sentinel 

      become: true